version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports: ["9200:9200"]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports: ["5601:5601"]

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
      - ./logstash/snort.conf:/usr/share/logstash/pipeline/snort.conf:ro
    ports: ["5000:5000"]

  snort:
    image: jasonish/snort:latest
    network_mode: "host"
    volumes:
      - ./snort/snort.conf:/etc/snort/snort.conf:ro
      - ./snort/rules:/etc/snort/rules:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: snort -c /etc/snort/snort.conf -i eth0 -A console
